name: Java CI with Maven and Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 1: Start Selenium Server with ChromeDriver (Windows)
    - name: Start Selenium Server with Chrome
      if: startsWith(matrix.os, 'windows-')
      run: |
        docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome:latest

    # Step 2: Set ChromeDriver PATH
    - name: Set ChromeDriver PATH
      run: echo "##[add-path]$HOME/bin"

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 3: Run Selenium tests on Windows
    - name: Run Selenium Tests
      run: mvn test -Dtest=test.TestCases
