name: Practo_Website_Testing_Selinium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 1: Start Selenium Grid with Chrome (Linux)
    - name: Start Selenium Grid with Chrome
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome-debug:latest

    # Step 2: Set ChromeDriver PATH
    - name: Set ChromeDriver PATH
      run: echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 3: Run Selenium tests on Linux
    - name: Run Selenium Tests
      if: startsWith(matrix.os, 'ubuntu-')
      run: mvn test -Dtest=test.TestCases
